[profile.release]
panic = 'unwind'

[[bin]]
name = 'substratee-node'
path = 'src/main.rs'

[build-dependencies]
vergen = '3'

[package]
authors = ["Supercomputing Systems AG <info@scs.ch>"]
build = 'build.rs'
edition = '2018'
name = 'substratee-node'
version = '2.0.0'

[dependencies]
derive_more = "0.14.0"
exit-future = '0.1'
futures = '0.1'
log = '0.4'
parity-codec = '3.3'
parking_lot = "0.8.0"
tokio = '0.1'
trie-root = '0.12.2'

[dependencies.basic-authorship]
git = 'https://github.com/paritytech/substrate'
package = 'substrate-basic-authorship'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.consensus]
git = 'https://github.com/paritytech/substrate'
package = 'substrate-consensus-aura'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.ctrlc]
features = ['termination']
version = '3.0'

[dependencies.inherents]
git = 'https://github.com/paritytech/substrate'
package = 'substrate-inherents'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.network]
git = 'https://github.com/paritytech/substrate'
package = 'substrate-network'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.substratee-node-runtime]
path = 'runtime'

[dependencies.primitives]
git = 'https://github.com/paritytech/substrate'
package = 'substrate-primitives'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.sr-io]
path = 'sr-tee-io'

[dependencies.substrate-cli]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.substrate-client]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.substrate-executor]
path = "substratee-executor"
package = 'substrate-executor'

[dependencies.substrate-service]
git = 'https://github.com/paritytech/substrate'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.transaction-pool]
git = 'https://github.com/paritytech/substrate'
package = 'substrate-transaction-pool'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[patch.'https://github.com/paritytech/substrate']
sr-io = { path = 'sr-tee-io' }
substrate-executor = { path = 'substratee-executor' }