[package]
authors = ['Supercomputing Systems']
build = 'build.rs'
edition = '2018'
name = 'substratee-node'
version = '1.0.0'

[build-dependencies]
vergen = '3'

[dependencies]
error-chain = '0.12'
exit-future = '0.1'
futures = '0.1'
log = '0.4'
parity-codec = '3.3'
parking_lot = '0.7.1'
tokio = '0.1'
trie-root = '0.12.2'

[dependencies.basic-authorship]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"
package = 'substrate-basic-authorship'

[dependencies.consensus]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"
package = 'substrate-consensus-aura'

[dependencies.ctrlc]
features = ['termination']
version = '3.0'

[dependencies.inherents]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"
package = 'substrate-inherents'

[dependencies.network]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"
package = 'substrate-network'

[dependencies.substratee-node-runtime]
path = 'runtime'

[dependencies.primitives]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"
package = 'substrate-primitives'

[dependencies.sr-io]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"

[dependencies.substrate-cli]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"

[dependencies.substrate-client]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"

[dependencies.substrate-executor]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"

[dependencies.substrate-service]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"

[dependencies.transaction-pool]
git = "https://github.com/brenzi/substrate.git" 
branch="global-allocator-feature"
package = 'substrate-transaction-pool'

[profile.release]
panic = 'unwind'

[[bin]]
name = 'substratee-node'
path = 'src/main.rs'
