[package]
name = "substratee-node"
version = "4.0.1"
authors = ["Supercomputing Systems AG <info@scs.ch>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "substratee-node"
path = "src/main.rs"

# to run cargo test with dev-dependencies it must be part of a workspace
#[workspace]
#members = [ "runtime",
#            "host_calls"]

[dependencies]
derive_more = "0.15.0"
futures = "0.1.29"
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
exit-future = "0.1.4"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"

[dependencies.sr-io]
git = "https://github.com/paritytech/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.substrate-cli]
git = "https://github.com/paritytech/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-primitives"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.substrate-executor]
git = "https://github.com/paritytech/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.substrate-service]
git = "https://github.com/paritytech/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.inherents]
git = "https://github.com/paritytech/substrate"
package = "substrate-inherents"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.transaction-pool]
git = "https://github.com/paritytech/substrate"
package = "substrate-transaction-pool"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.network]
git = "https://github.com/paritytech/substrate"
package = "substrate-network"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.babe]
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-babe"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.babe-primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-consensus-babe-primitives"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.grandpa]
git = "https://github.com/paritytech/substrate"
package = "substrate-finality-grandpa"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.grandpa-primitives]
git = "https://github.com/paritytech/substrate"
package = "substrate-finality-grandpa-primitives"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.substrate-client]
git = "https://github.com/paritytech/substrate"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.basic-authorship]
git = "https://github.com/paritytech/substrate"
package = "substrate-basic-authorship"
rev = "f17d023bbe179f15678ac9989f471c9b18917e17"

[dependencies.substratee-node-runtime]
path = "runtime"
features = ["enable_host_calls"]

[patch."https://github.com/paritytech/substrate"]
sr-io = { package = "sr-io", path = "sr-tee-io", default-features=false }
substrate-executor = { path = "substratee-executor", default-features=false}

[build-dependencies]
vergen = "3.0.4"
