[features]
default = ['std']
std = [
    'parity-codec/std',
    'client/std',
    'rstd/std',
    'runtime-io/std',
    'support/std',
    'balances/std',
    'executive/std',
    'aura/std',
    'indices/std',
    'primitives/std',
    'runtime-primitives/std',
    'system/std',
    'timestamp/std',
    'sudo/std',
    'version/std',
    'serde',
    'safe-mix/std',
    'consensus-aura/std',
    'offchain-primitives/std',
    'consensus_authorities/std',
]
no_global_allocator = [
	"rstd/no_global_allocator",
]
no_panic_handler = [
    "runtime-io/no_panic_handler"
]
no_oom = [
    "runtime-io/no_oom"
]

[package]
authors = ['Supercomputing Systems']
edition = '2018'
name = 'substratee-node-runtime'
version = '1.0.0'
[dependencies.aura]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'srml-aura'

[dependencies.balances]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'srml-balances'

[dependencies.client]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'substrate-client'

[dependencies.consensus]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'srml-consensus'

[dependencies.consensus-aura]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'substrate-consensus-aura-primitives'

[dependencies.consensus_authorities]
default-features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'substrate-consensus-authorities'

[dependencies.executive]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'srml-executive'

[dependencies.indices]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'srml-indices'

[dependencies.offchain-primitives]
default-features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'substrate-offchain-primitives'

[dependencies.parity-codec]
default-features = false
features = ['derive']
version = '3.3'

[dependencies.primitives]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'substrate-primitives'

[dependencies.rstd]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'sr-std'

[dependencies.runtime-io]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'sr-io'

[dependencies.runtime-primitives]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'sr-primitives'

[dependencies.safe-mix]
default-features = false
version = '1.0'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0'

[dependencies.sudo]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'srml-sudo'

[dependencies.support]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'srml-support'

[dependencies.system]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'srml-system'

[dependencies.timestamp]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'srml-timestamp'

[dependencies.version]
default_features = false
git = "https://github.com/paritytech/substrate.git" 
rev="6e67eff0653677d3d01980ca822c4b8a227914a3"
package = 'sr-version'
