[dependencies.aura]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'srml-aura'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.balances]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'srml-balances'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.client]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'substrate-client'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.consensus]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'srml-consensus'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.consensus-aura]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'substrate-consensus-aura-primitives'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.consensus_authorities]
default-features = false
git = 'https://github.com/paritytech/substrate'
package = 'substrate-consensus-authorities'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.executive]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'srml-executive'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.indices]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'srml-indices'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.offchain-primitives]
default-features = false
git = 'https://github.com/paritytech/substrate'
package = 'substrate-offchain-primitives'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.parity-codec]
default-features = false
features = ['derive']
version = '3.3'

[dependencies.primitives]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'substrate-primitives'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.rstd]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'sr-std'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.runtime-io]
default_features = false
path = '../sr-tee-io'
package = 'sr-io'

[dependencies.runtime-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'sr-primitives'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.safe-mix]
default-features = false
version = '1.0'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0'

[dependencies.sudo]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'srml-sudo'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'srml-support'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'srml-system'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.timestamp]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'srml-timestamp'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[dependencies.version]
default_features = false
git = 'https://github.com/paritytech/substrate'
package = 'sr-version'
rev = '56b0273fd48b4e742e9da7317bc8e132a740b684'

[features]
default = ['std']
std = [
    'parity-codec/std',
    'client/std',
    'rstd/std',
    'runtime-io/std',
    'support/std',
    'balances/std',
    'executive/std',
    'aura/std',
    'indices/std',
    'primitives/std',
    'runtime-primitives/std',
    'system/std',
    'timestamp/std',
    'sudo/std',
    'version/std',
    'serde',
    'safe-mix/std',
    'consensus-aura/std',
    'offchain-primitives/std',
    'consensus_authorities/std',
]
no_global_allocator = [
	"rstd/no_global_allocator",
]
no_panic_handler = [
    "runtime-io/no_panic_handler"
]
no_oom = [
    "runtime-io/no_oom"
]

[package]
authors = ["Supercomputing Systems AG <info@scs.ch>"]
edition = '2018'
name = 'substratee-node-runtime'
version = '2.0.0'
